### ISSUE TITLE
Problem startng the org -agent: Error: open /opt/orb/agent.yaml: permission denied

### ISSUE THREAD

**Issue by misch42** [netboxlabs/orb-agent#36]
Hi,

I installed orb-agent according to the getting started doc.

When I run the agent, I get the error that the agent cannot access to agent.yaml file:

docker run -v /root/:/opt/orb/ -e DIODE_API_KEY=xxxx netboxlabs/orb-agent:latest run -c /opt/orb/agent.yaml
Contains configuration argument parameter
Setting default_pcap as visor tap
Running with config file parameter
Starting orb-agent : /usr/local/bin/orb-agent with args 3
Error: open /opt/orb/agent.yaml: permission denied
14 is not running

ls -la /opt/orb/agent.yaml 
-rw-rw-rw- 1 root root 353 Dec 20 12:04 /opt/orb/agent.yaml

Any ideas?

**Comment by leoparente** [comment]
The problem is permissions on mounting folder `/root`; changing it to any other folder like `/opt/orb` works.
